name: "CodeQL + ATM analysis"

on:
  push:
    paths:
      - '.github/workflows/codeql-analysis-with-atm-query-suite.yml'
  workflow_dispatch:

env:
  BASE_URL: 'https://atmcodeqlpublicdata.blob.core.windows.net/atmpublic/query-suite/v1.0.0-rc1+368448f'
  CLI_ADDITIONS_CHECKSUM: 'cd1225fa4a61c35b9dd51e3324df4facdb9633d0a86de7be636d1225ccf88713e04a1501bdc2f23b0313224396163eb0113185fdf59fcc35207cc72f1afb9bda'
  QLPACK_CHECKSUM: 'd88295e6ffb20d64eb458f984ef2fb0b9ab6ef4dd3f2a5f5d778444c77cc919e402b72a97bd7fd201424be081c25f9e9795e796b84f7a0985ffb0ab45d385fe7'

jobs:
  CodeQL-Build:
    runs-on: ubuntu-latest-xl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ATM query pack
        run: |
          qlpack_url="${BASE_URL}/codeql-atm-qlpack.tar.gz"
          echo "Attempting to download ATM query pack from ${qlpack_url}"
          azcopy10 cp "${qlpack_url}" qlpack.tar.gz
          if ! echo "${QLPACK_CHECKSUM} *qlpack.tar.gz" | shasum -c; then
            echo "::error::Failed to validate ATM query pack checksum. Expected ${QLPACK_CHECKSUM}, was " \
              "$(sha512sum -b qlpack.tar.gz | awk '{ print $1 }')"
            exit 1
          fi
          mkdir -p .github/codeql
          atm_qlpack_path=".github/codeql/codeql-javascript-atm"
          mkdir ${atm_qlpack_path}
          tar -xvzf qlpack.tar.gz -C ${atm_qlpack_path}
          rm qlpack.tar.gz
          ls -lR ${atm_qlpack_path}
          # Add ATM query pack to the CodeQL search path
          CODEQL_CONFIG_FILE="${RUNNER_TEMP}/codeql_config"
          echo "CODEQL_CONFIG_FILE=${CODEQL_CONFIG_FILE}" >> ${GITHUB_ENV}
          echo "--search-path ${atm_qlpack_path}" >> ${CODEQL_CONFIG_FILE}
          echo "ATM CodeQL CLI config file contents:"
          cat ${CODEQL_CONFIG_FILE}
          echo "name: \"ATM CodeQL config\"" > .github/codeql/codeql-config.yml
          echo "disable-default-queries: true" >> .github/codeql/codeql-config.yml
          echo "queries:" >> .github/codeql/codeql-config.yml
          echo "  - uses: ./${atm_qlpack_path}/codeql-suites/javascript-atm-code-scanning.qls" >> .github/codeql/codeql-config.yml
          echo "ATM Code Scanning config file contents:"
          cat .github/codeql/codeql-config.yml
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        id: codeql-init
        uses: github/codeql-action/init@v1
        with:
          config-file: ./.github/codeql/codeql-config.yml
          languages: javascript
          tools: https://github.com/dsp-testing/codeml-testing/releases/download/codeql-bundle-20210615/codeql-bundle-linux64.tar.gz
          db-location: '${{ github.workspace }}/codeql-database'

      - name: Install ATM CLI additions
        env:
          CODEQL_PATH: ${{ steps.codeql-init.outputs.codeql-path }}
        run: |
          cli_root="$(dirname ${CODEQL_PATH})"
          echo "Using CodeQL CLI root at ${cli_root}"
          cli_additions_url="${BASE_URL}/codeql-atm-cli-additions.tar.gz"
          echo "Attempting to download ATM CLI additions from ${cli_additions_url}"
          azcopy10 cp "${cli_additions_url}" cli-additions.tar.gz
          if ! echo "${CLI_ADDITIONS_CHECKSUM} *cli-additions.tar.gz" | sha512sum -c; then
            echo "::error::Failed to validate ATM CLI additions checksum. Expected ${CLI_ADDITIONS_CHECKSUM}, was " \
              "$(sha512sum -b cli-additions.tar.gz | awk '{ print $1 }')"
            exit 1
          fi
          tar -xvzf cli-additions.tar.gz -C ${cli_root}
          rm cli-additions.tar.gz
          ls -lR ${cli_root}/lib-extra
          ls -lR ${cli_root}/ml-models
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        with:
          ram: 5120
          output: '.github/codeql/codeql-javascript-atm/results'
          threads: 1

      - name: Upload SARIF results output
        uses: actions/upload-artifact@v2
        with:
          name: javascript-atm.sarif
          path: .github/codeql/codeql-javascript-atm/results/*.sarif
      
      - name: Upload CodeQL database
        uses: actions/upload-artifact@v2
        with:
          name: codeql-database
          path: '${{ github.workspace }}/codeql-database'
